name: Deploy to staging
on:
  push:
    branches: 
      - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Redeploy everything to the staging cluster 
    steps:
      - name: SSH into server
        run: |
          echo "${{secrets.id_ed25519_aws}}" > ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{secrets.known_hosts}}" > ~/.ssh/known_hosts
          chmod 700 ~/ssh_key
          
      - name: SSH into server and redeploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.233.140.29 << 'EOF'
          cd Monorepo-CICD-Testing
          git pull
          pnpm install --frozen-lockfile
          pnpm build
          pm2 restart web
          pm2 restart ws
          pm2 restart http
          EOF